import { Inter, Maven_Pro } from "next/font/google";
import "./globals.css";
import LocationProvider from "@/utils/location-provider";

const inter = Inter({
  subsets: ['latin'],
  weight: ['400', '500', '700'], 
  variable: '--font-inter', 
  display: 'swap', 
})

const maven = Maven_Pro({
  subsets: ['latin'],
  weight: ['400', '500', '700'],
  display: 'swap',
});

export const metadata = {
  title: "Dexwin Home page",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en" className={maven.className}>
      <body className={` ${inter.variable} antialiased`} >
        <LocationProvider >
          {children}    
        </LocationProvider>
      </body>
    </html>
  );
}
